<a href="https://colab.research.google.com/github/j019/Practical-Machine-Learning-/blob/main/Day2/customerSegmentation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from pandas import read_csv

In [11]:
df = read_csv('/content/customer_data.csv', encoding='iso-8859-1')

In [12]:
df.shape

(541909, 8)

In [9]:
df.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [13]:
df.drop(columns=['Description'], inplace=True)

In [15]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [16]:
df.dropna(inplace=True)

In [17]:
df.shape

(406829, 7)

In [18]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Quantity', 'InvoiceDate', 'UnitPrice',
       'CustomerID', 'Country'],
      dtype='object')

In [19]:
df['Price'] = df['Quantity']*df['UnitPrice']

In [20]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Quantity', 'InvoiceDate', 'UnitPrice',
       'CustomerID', 'Country', 'Price'],
      dtype='object')

# Unique Invoices
- as_index = False or reset_index

In [31]:
df1 = df.groupby(['InvoiceNo','InvoiceDate','CustomerID'],as_index=False).agg({
    'Price': 'sum'})

In [32]:
df1.head()

  InvoiceNo     InvoiceDate  CustomerID   Price
0    536365  12/1/2010 8:26     17850.0  139.12
1    536366  12/1/2010 8:28     17850.0   22.20
2    536367  12/1/2010 8:34     13047.0  278.73
3    536368  12/1/2010 8:34     13047.0   70.05
4    536369  12/1/2010 8:35     13047.0   17.85

In [33]:
df1.shape

(22221, 4)

- CustomerId, total no of invoices, total spent
- std dev of spent in invoice
- days from the last invoice

In [37]:
df1= df1.loc[df1['Price'] > 0,:]

In [39]:
df1.shape

(18562, 6)

In [40]:
#df1['Total_Invoices'] = df1.groupby('CustomerID')['InvoiceNo'].transform('count')
#df1['Total_spent'] = df1.groupby('CustomerID')['Price'].transform('sum')
#df['Variance_spent'] = df1.groupby('CustomerID')['Price'].transform('std')
df1.groupby('CustomerID').agg({'Price':'sum','InvoiceNo':'count','InvoiceDate':'max'})

               Price  InvoiceNo      InvoiceDate
CustomerID
12346.0     77183.60          1  1/18/2011 10:01
12347.0      4310.00          7    8/2/2011 8:48
12348.0      1797.24          4  9/25/2011 13:13
12349.0      1757.55          1  11/21/2011 9:51
12350.0       334.40          1   2/2/2011 16:01
...              ...        ...              ...
18280.0       180.60          1    3/7/2011 9:52
18281.0        80.82          1  6/12/2011 10:53
18282.0       178.05          2   8/5/2011 13:35
18283.0      2094.88         16   9/5/2011 12:35
18287.0      1837.28          3  5/22/2011 10:39

[4338 rows x 3 columns]